### ISSUE TITLE
Cockpit don't create a specific specs for the cloudspace

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#147] opened 2016-07-24 10:34 UTC
**Description**
Cockpit always creates a CS with Unlimited specs even if the bp describe specific properties. 
The following bp has a specific properties : 

> g8client__dubai:
>   g8.url: 'du-conv-2.demo.greenitglobe.com'
>   g8.login: 'gig'
>   g8.password: 'KrOe6gE9K5nCQdmretfXnj'
>   g8.account: 'gig'
> 
> vdc__CHECKCAPS:
>   g8.client.name: 'dubai'
>   maxMemoryCapacity: 2
>   maxVDiskCapacity: 10
>   maxCPUCapacity: 2
>   maxNASCapacity: 20
>   maxArchiveCapacity: 20
>   maxNetworkOptTransfer: 5
>   maxNetworkPeerTransfer: 15
>   maxNumPublicIP: 1

**Actual result**
![screenshot from 2016-07-24 12-33-07](https://cloud.githubusercontent.com/assets/17981089/17083274/2d770be6-51a3-11e6-92a0-2aeb941060b8.png)

**Comment by xmonader** [comment] 2016-07-27 07:41
It's fixed. We couldn't reproduce that today.

**Comment by zaibon** [comment] 2016-08-23 09:00
@islamTaha12 @xmonader 
Can we test this again and see if the issue has been fixed in the HRD please.

**Comment by zaibon** [comment] 2016-11-16 11:59
we don't force the cockpit to be installed on a VM anymore so we don't create the vdc either

**Closed by zaibon** 2016-11-16 11:59 UTC
Labels: priority_critical, type_bug
