### ISSUE TITLE
form behavior for blueprints change request

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#305] opened 2016-12-05 13:53 UTC
![image](https://cloud.githubusercontent.com/assets/6021844/20887342/9c48be6e-bb13-11e6-8864-e10464bdf41f.png)

- call apply
- in actions
    - have install (which dus install action & run)
    - keep run
    - add cleanup (which removes logs & run info)

**Comment by rkhamis** [comment] 2016-12-07 14:11
Duplicate of https://github.com/Jumpscale/jscockpit/issues/301

**Closed by rkhamis** 2016-12-07 14:11 UTC
