### ISSUE TITLE
explorer not working

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#294] opened 2016-12-04 14:57 UTC
![image](https://cloud.githubusercontent.com/assets/6021844/20866976/84f4744e-ba53-11e6-8eb4-91808a1f309f.png)

**Comment by zaibon** [comment] 2016-12-05 05:10
duplicate of  https://github.com/Jumpscale/jscockpit/issues/295

**Closed by zaibon** 2016-12-05 05:10 UTC
Labels: priority_major
