### ISSUE TITLE
Cockpit can't create a CS with a capital letters

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#146] opened 2016-07-24 10:24 UTC
**Description**
Cockpit can't create a CS with a capital letters. The following bp has a CS name with a capital letters

> g8client__dubai:
  g8.url: 'du-conv-2.demo.greenitglobe.com'
  g8.login: 'gig'
  g8.password: 'KrOe6gE9K5nCQdmretfXnj'
  g8.account: 'gig'

> vdc__CHECKCAPS:
>   g8.client.name: 'dubai'
>   maxMemoryCapacity: 2
>   maxVDiskCapacity: 10
>   maxCPUCapacity: 2
>   maxNASCapacity: 20
>   maxArchiveCapacity: 20
>   maxNetworkOptTransfer: 5
>   maxNetworkPeerTransfer: 15
>   maxNumPublicIP: 1

**Actual result**
![screenshot from 2016-07-24 12-23-04](https://cloud.githubusercontent.com/assets/17981089/17083240/c57dc364-51a1-11e6-99e7-e36218bedd33.png)

**Comment by xmonader** [comment] 2016-07-24 10:41
Duplicate of #62

**Closed by xmonader** 2016-07-24 10:41 UTC
