### ISSUE TITLE
copy/document mode modular way of installing

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jscockpit#22] opened 2016-06-10 06:36 UTC
see reem

principle
- flexible way to get to a deployed OS (preinstalled with known sshkey, openvcloud, packet.net)
- start from a deployed OS (in a node)
- deploy cockpit as docker that OS

**Comment by despiegk** [comment] 2016-06-10 06:36
dont forget documentation

**Comment by rkhamis** [comment] 2016-06-13 15:51
Duplicate of #295 and #163

**Closed by rkhamis** 2016-06-13 15:51 UTC
Labels: priority_normal, type_feature
