### ISSUE TITLE
cockpit_portal: No home page when user is not identified.

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jscockpit#216] opened 2016-11-07 04:53 UTC
When not identified the user should not see a `Access Denied.` message but a nice home page that welcome and invite him to sign in.

**Comment by FastGeert** [comment] 2016-11-27 16:38
Duplicate of https://github.com/Jumpscale/jumpscale_portal8/issues/58

**Closed by FastGeert** 2016-11-27 16:38 UTC
Labels: type_bug
