### ISSUE TITLE
Delete button doesn't work on Instances page

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#156] opened 2016-07-25 08:34 UTC
Check the Instances page of repo "yves": https://moehaha.barcelona.aydo.com/cockpit/cockpit/Instances?ayspath=yves

Click **Delete** any of the "4..." repo's => nothing happens

![screen shot 2016-07-25 at 10 31 51](https://cloud.githubusercontent.com/assets/13795109/17095089/185d4986-5253-11e6-8db5-289cb556138e.png)

**Comment by zaibon** [comment] 2016-07-25 10:39
caused by https://github.com/Jumpscale/jumpscale_portal8/issues/77
will be fixed once https://github.com/Jumpscale/jumpscale_portal8/pull/78 is merged

**Closed** 2016-07-25 11:08 UTC
Labels: priority_urgent, type_bug
